Import of MLEHMANN/Gimp-0.97 from CPAN.
gitpan-cpan-distribution: Gimp
gitpan-cpan-version:      0.97
gitpan-cpan-path:         MLEHMANN/Gimp-0.97.tar.gz
gitpan-cpan-author:       MLEHMANN
gitpan-cpan-maturity:     released

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20,7 +20,11 @@ ac_help="$ac_help
 ac_help="$ac_help
   --with-libs=DIR         Additionally search for libraries in dir in DIR (optional)"
 ac_help="$ac_help
-  --with-glib-prefix=DIR  Prefix where GLIB is installed (optional)"
+  --with-gimp-prefix=PFX   Prefix where GIMP is installed (optional)"
+ac_help="$ac_help
+  --with-gimp-exec-prefix=PFX Exec prefix where GIMP is installed (optional)"
+ac_help="$ac_help
+  --disable-gimptest       Do not try to compile and run a test GIMP program"
 
 # Initialize some variables set by options.
 # The variables have the same names as the options, with
@@ -560,19 +564,16 @@ if test "${with_libs+set}" = set; then
 fi
 
 
-# Check whether --with-glib-prefix or --without-glib-prefix was given.
-if test "${with_glib_prefix+set}" = set; then
-  withval="$with_glib_prefix"
-  CFLAGS="$CFLAGS -I$with_glib_prefix/include" LIBS="$LIBS -L$with_glib_prefix/libs"
-fi
+#AC_CHECK_PROGS(GTKCONFIG,gtk-config,gtk-config)
+#GTK_CFLAGS="`$GTKCONFIG --cflags`"
+#GTK_LIBS="`$GTKCONFIG --libs`"
 
-
-for ac_prog in perl5.004_01 perl5.004 perl5 perl
+for ac_prog in perl5.004_04 perl5.004 perl5 perl
 do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:576: checking for $ac_word" >&5
+echo "configure:577: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_PERL'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -606,7 +607,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:610: checking for $ac_word" >&5
+echo "configure:611: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_GIMP'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -642,12 +643,12 @@ eval `$PERL -V:cc`
 for ac_func in vsnprintf
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
-echo "configure:646: checking for $ac_func" >&5
+echo "configure:647: checking for $ac_func" >&5
 if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 651 "configure"
+#line 652 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char $ac_func(); below.  */
@@ -670,7 +671,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:674: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:675: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -697,90 +698,233 @@ fi
 done
 
 
-echo $ac_n "checking for g_malloc in -lglib-1.1""... $ac_c" 1>&6
-echo "configure:702: checking for g_malloc in -lglib-1.1" >&5
-ac_lib_var=`echo glib-1.1'_'g_malloc | sed 'y%./+-%__p_%'`
-if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
+# Check whether --with-gimp-prefix or --without-gimp-prefix was given.
+if test "${with_gimp_prefix+set}" = set; then
+  withval="$with_gimp_prefix"
+  gimptool_prefix="$withval"
+else
+  gimptool_prefix=""
+fi
+
+# Check whether --with-gimp-exec-prefix or --without-gimp-exec-prefix was given.
+if test "${with_gimp_exec_prefix+set}" = set; then
+  withval="$with_gimp_exec_prefix"
+  gimptool_exec_prefix="$withval"
+else
+  gimptool_exec_prefix=""
+fi
+
+# Check whether --enable-gimptest or --disable-gimptest was given.
+if test "${enable_gimptest+set}" = set; then
+  enableval="$enable_gimptest"
+  :
+else
+  enable_gimptest=yes
+fi
+
+
+  if test x$gimptool_exec_prefix != x ; then
+     gimptool_args="$gimptool_args --exec-prefix=$gimptool_exec_prefix"
+     if test x${GIMPTOOL+set} != xset ; then
+        GIMPTOOL=$gimptool_exec_prefix/bin/gimptool
+     fi
+  fi
+  if test x$gimptool_prefix != x ; then
+     gimptool_args="$gimptool_args --prefix=$gimptool_prefix"
+     if test x${GIMPTOOL+set} != xset ; then
+        GIMPTOOL=$gimptool_prefix/bin/gimptool
+     fi
+  fi
+
+  # Extract the first word of "gimptool", so it can be a program name with args.
+set dummy gimptool; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:743: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_GIMPTOOL'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
-  ac_save_LIBS="$LIBS"
-LIBS="-lglib-1.1  $LIBS"
-cat > conftest.$ac_ext <<EOF
-#line 710 "configure"
+  case "$GIMPTOOL" in
+  /*)
+  ac_cv_path_GIMPTOOL="$GIMPTOOL" # Let the user override the test with a path.
+  ;;
+  ?:/*)			 
+  ac_cv_path_GIMPTOOL="$GIMPTOOL" # Let the user override the test with a dos path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS="${IFS}:"
+  for ac_dir in $PATH; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_GIMPTOOL="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  test -z "$ac_cv_path_GIMPTOOL" && ac_cv_path_GIMPTOOL="no"
+  ;;
+esac
+fi
+GIMPTOOL="$ac_cv_path_GIMPTOOL"
+if test -n "$GIMPTOOL"; then
+  echo "$ac_t""$GIMPTOOL" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+  min_gimp_version=1.0.0
+  echo $ac_n "checking for GIMP - version >= $min_gimp_version""... $ac_c" 1>&6
+echo "configure:777: checking for GIMP - version >= $min_gimp_version" >&5
+  no_gimp=""
+  if test "$GIMPTOOL" = "no" ; then
+    no_gimp=yes
+  else
+    GIMP_CFLAGS=`$GIMPTOOL $gimptool_args --cflags`
+    GIMP_LIBS=`$GIMPTOOL $gimptool_args --libs`
+    gimptool_major_version=`$GIMPTOOL $gimptool_args --version | \
+           sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\)/\1/'`
+    gimptool_minor_version=`$GIMPTOOL $gimptool_args --version | \
+           sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\)/\2/'`
+    gimptool_micro_version=`$GIMPTOOL $gimptool_args --version | \
+           sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\)/\3/'`
+    if test "x$enable_gimptest" = "xyes" ; then
+      ac_save_CFLAGS="$CFLAGS"
+      ac_save_LIBS="$LIBS"
+      CFLAGS="$CFLAGS $GIMP_CFLAGS"
+      LIBS="$LIBS $GIMP_LIBS"
+      rm -f conf.gimptest
+      if test "$cross_compiling" = yes; then
+  echo $ac_n "cross compiling; assumed OK... $ac_c"
+else
+  cat > conftest.$ac_ext <<EOF
+#line 800 "configure"
 #include "confdefs.h"
-/* Override any gcc2 internal prototype to avoid an error.  */
-/* We use char because int might match the return type of a gcc2
-    builtin and then its argument prototype would still apply.  */
-char g_malloc();
+
+#include <stdio.h>
+#include <stdlib.h>
+#include <libgimp/gimp.h>
+
+GPlugInInfo PLUG_IN_INFO =
+{
+  NULL,  /* init_proc */
+  NULL,  /* quit_proc */
+  NULL,  /* query_proc */
+  NULL   /* run_proc */
+};
+
+int main ()
+{
+  int major, minor, micro;
+  char *tmp_version;
+
+  system ("touch conf.gimptest");
+
+  /* HP/UX 9 (%@#!) writes to sscanf strings */
+  tmp_version = g_strdup("$min_gimp_version");
+  if (sscanf(tmp_version, "%d.%d.%d", &major, &minor, &micro) != 3) {
+     printf("%s, bad version string\n", "$min_gimp_version");
+     exit(1);
+   }
+
+    if (($gimptool_major_version > major) ||
+        (($gimptool_major_version == major) && ($gimptool_minor_version > minor)) ||
+        (($gimptool_major_version == major) && ($gimptool_minor_version == minor) && ($gimptool_micro_version >= micro)))
+    {
+      return 0;
+    }
+  else
+    {
+      printf("\n*** 'gimptool --version' returned %d.%d.%d, but the minimum version\n", $gimptool_major_version, $gimptool_minor_version, $gimptool_micro_version);
+      printf("*** of GIMP required is %d.%d.%d. If gimptool is correct, then it is\n", major, minor, micro);
+      printf("*** best to upgrade to the required version.\n");
+      printf("*** If gimptool was wrong, set the environment variable GIMPTOOL\n");
+      printf("*** to point to the correct copy of gimptool, and remove the file\n");
+      printf("*** config.cache before re-running configure\n");
+      return 1;
+    }
+}
+
+
+EOF
+if { (eval echo configure:849: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
+then
+  :
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+  no_gimp=yes
+fi
+rm -fr conftest*
+fi
+
+       CFLAGS="$ac_save_CFLAGS"
+       LIBS="$ac_save_LIBS"
+     fi
+  fi
+  if test "x$no_gimp" = x ; then
+     echo "$ac_t""yes" 1>&6
+     :     
+  else
+     echo "$ac_t""no" 1>&6
+     if test "$GIMPTOOL" = "no" ; then
+       echo "*** The gimptool script installed by GIMP could not be found"
+       echo "*** If GIMP was installed in PREFIX, make sure PREFIX/bin is in"
+       echo "*** your path, or set the GIMPTOOL environment variable to the"
+       echo "*** full path to gimptool."
+     else
+       if test -f conf.gimptest ; then
+        :
+       else
+          echo "*** Could not run GIMP test program, checking why..."
+          CFLAGS="$CFLAGS $GIMP_CFLAGS"
+          LIBS="$LIBS $GIMP_LIBS"
+          cat > conftest.$ac_ext <<EOF
+#line 883 "configure"
+#include "confdefs.h"
+
+#include <stdio.h>
+#include <libgimp/gimp.h>
 
 int main() {
-g_malloc()
+ return 0; 
 ; return 0; }
 EOF
-if { (eval echo configure:721: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:893: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=yes"
+   echo "*** The test program compiled, but did not run. This usually means"
+          echo "*** that the run-time linker is not finding GIMP or finding the wrong"
+          echo "*** version of GIMP. If it is not finding GIMP, you'll need to set your"
+          echo "*** LD_LIBRARY_PATH environment variable, or edit /etc/ld.so.conf to point"
+          echo "*** to the installed location  Also, make sure you have run ldconfig if that"
+          echo "*** is required on your system"
+	  echo "***"
+          echo "*** If you have an old version installed, it is best to remove it, although"
+          echo "*** you may also be able to get things to work by modifying LD_LIBRARY_PATH"
 else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
   rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=no"
+   echo "*** The test program failed to compile or link. See the file config.log for the"
+          echo "*** exact error that occured. This usually means GIMP was incorrectly installed"
+          echo "*** or that you have moved GIMP since it was installed. In the latter case, you"
+          echo "*** may want to edit the gimptool script: $GIMPTOOL" 
 fi
 rm -f conftest*
-LIBS="$ac_save_LIBS"
-
-fi
-if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
-  echo "$ac_t""yes" 1>&6
-  LIBS="$LIBS -lglib-1.1"
-else
-  echo "$ac_t""no" 1>&6
-echo $ac_n "checking for g_malloc in -lglib""... $ac_c" 1>&6
-echo "configure:740: checking for g_malloc in -lglib" >&5
-ac_lib_var=`echo glib'_'g_malloc | sed 'y%./+-%__p_%'`
-if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  ac_save_LIBS="$LIBS"
-LIBS="-lglib  $LIBS"
-cat > conftest.$ac_ext <<EOF
-#line 748 "configure"
-#include "confdefs.h"
-/* Override any gcc2 internal prototype to avoid an error.  */
-/* We use char because int might match the return type of a gcc2
-    builtin and then its argument prototype would still apply.  */
-char g_malloc();
-
-int main() {
-g_malloc()
-; return 0; }
-EOF
-if { (eval echo configure:759: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
-  rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=yes"
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=no"
-fi
-rm -f conftest*
-LIBS="$ac_save_LIBS"
-
-fi
-if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
-  echo "$ac_t""yes" 1>&6
-  LIBS="$LIBS -lglib"
-else
-  echo "$ac_t""no" 1>&6
-{ echo "configure: error: unable to find glib" 1>&2; exit 1; }
-fi
-
-fi
+          CFLAGS="$ac_save_CFLAGS"
+          LIBS="$ac_save_LIBS"
+       fi
+     fi
+     GIMP_CFLAGS=""
+     GIMP_LIBS=""
+     { echo "configure: error: ** unable to find gimp" 1>&2; exit 1; }
+  fi
+  
+  
+  rm -f conf.gimptest
 
 
 echo $ac_n "checking how to run the C preprocessor""... $ac_c" 1>&6
-echo "configure:784: checking how to run the C preprocessor" >&5
+echo "configure:928: checking how to run the C preprocessor" >&5
 # On Suns, sometimes $CPP names a directory.
 if test -n "$CPP" && test -d "$CPP"; then
   CPP=
@@ -795,13 +939,13 @@ else
   # On the NeXT, cc -E runs the code through the compiler's parser,
   # not just through cpp.
   cat > conftest.$ac_ext <<EOF
-#line 799 "configure"
+#line 943 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:805: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:949: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   :
@@ -812,13 +956,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -E -traditional-cpp"
   cat > conftest.$ac_ext <<EOF
-#line 816 "configure"
+#line 960 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:822: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:966: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   :
@@ -841,12 +985,12 @@ fi
 echo "$ac_t""$CPP" 1>&6
 
 echo $ac_n "checking for ANSI C header files""... $ac_c" 1>&6
-echo "configure:845: checking for ANSI C header files" >&5
+echo "configure:989: checking for ANSI C header files" >&5
 if eval "test \"`echo '$''{'ac_cv_header_stdc'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 850 "configure"
+#line 994 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 #include <stdarg.h>
@@ -854,7 +998,7 @@ else
 #include <float.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:858: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1002: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -871,7 +1015,7 @@ rm -f conftest*
 if test $ac_cv_header_stdc = yes; then
   # SunOS 4.x string.h does not declare mem*, contrary to ANSI.
 cat > conftest.$ac_ext <<EOF
-#line 875 "configure"
+#line 1019 "configure"
 #include "confdefs.h"
 #include <string.h>
 EOF
@@ -889,7 +1033,7 @@ fi
 if test $ac_cv_header_stdc = yes; then
   # ISC 2.0.2 stdlib.h does not declare free, contrary to ANSI.
 cat > conftest.$ac_ext <<EOF
-#line 893 "configure"
+#line 1037 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 EOF
@@ -910,7 +1054,7 @@ if test "$cross_compiling" = yes; then
   :
 else
   cat > conftest.$ac_ext <<EOF
-#line 914 "configure"
+#line 1058 "configure"
 #include "confdefs.h"
 #include <ctype.h>
 #define ISLOWER(c) ('a' <= (c) && (c) <= 'z')
@@ -921,7 +1065,7 @@ if (XOR (islower (i), ISLOWER (i)) || toupper (i) != TOUPPER (i)) exit(2);
 exit (0); }
 
 EOF
-if { (eval echo configure:925: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1069: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
 then
   :
 else
@@ -948,17 +1092,17 @@ for ac_hdr in libgimp/gimp.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:952: checking for $ac_hdr" >&5
+echo "configure:1096: checking for $ac_hdr" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 957 "configure"
+#line 1101 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:962: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1106: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -985,8 +1129,10 @@ fi
 done
 
 
-# just pretend libgimp is there for now
-LIBS="$LIBS -lgimp"
+
+
+
+
 
 
 
@@ -1123,6 +1269,9 @@ s%@infodir@%$infodir%g
 s%@mandir@%$mandir%g
 s%@PERL@%$PERL%g
 s%@GIMP@%$GIMP%g
+s%@GIMPTOOL@%$GIMPTOOL%g
+s%@GIMP_CFLAGS@%$GIMP_CFLAGS%g
+s%@GIMP_LIBS@%$GIMP_LIBS%g
 s%@CPP@%$CPP%g
 
 CEOF
